config/routes.rb
Rails.application.routes.draw do

    Rails.application.routes.draw do
      devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
    end

  resources :eurekas
  resources :classificas
  resources :bet_puntates
  resources :bets
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'schedine' => 'bet_puntates#schedine'

  get 'bilancio' => 'eurekas#bilancio'

  get 'bilancio_edit' => 'eurekas#bilancio_edit'

end

app/models/bet.rb
class Bet < ActiveRecord::Base
	belongs_to :user
	has_many :bet_puntates

	has_attached_file :logo_in, styles: { medium: "300x>", thumb: "10x>" }
  validates_attachment_content_type :logo_in, content_type: /\Aimage\/.*\z/

  has_attached_file :logo_out, styles: { medium: "300x>", thumb: "10x>" }
  validates_attachment_content_type :logo_out, content_type: /\Aimage\/.*\z/
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @appoggio = Bet.order('n_giornata DESC').limit(10)
    @bets = Bet.all.order('n_giornata DESC').paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @bet = current_user.bets.build
  end

  def edit
  end

  def create
    @bet = current_user.bets.build(bet_params)
    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'L ''evento è stato aggiunto alla tua schedina.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if bet_params[:chiudi_concorso] == "true"
        @appoggio = Bet.find_by(id: bet_params[:id])
        #@appoggio.each do |appo|
          if @appoggio.update(bet_params)
            format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
          else
            format.html { render :edit }
          end          

        #end
      end

      #if @bet.update(bet_params)
      #  format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
      #else
      #  format.html { render :edit }
      #end
    end
  end

  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: 'Bet was successfully destroyed.' }
    end
  end

  private
    def set_bet
      @bet = Bet.find_by(id: params[:id])
      @bet_puntate = BetPuntate.find_by(id: params[:id])
    end

    def bet_params
      params.require(:bet).permit(:id, :evento, :vittoria, :pareggio, :sconfitta, :data, :logo_in, :logo_out, :n_giornata, :chiudi_concorso, :risultato)
    end

    def check_user
      if current_user != @bet.user 
        redirect_to root_url, alert: "Scusa ma non ai accesso a questa pagina"
      end
    end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for @bet, html: { multipart: true } do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :n_giornata %><br>
    <%= f.text_field :n_giornata %>
  </div>  

  <div class="field">
    <%= f.label :evento %><br>
    <%= f.text_field :evento %>
    <%= f.file_field :logo_in %>
    <%= f.file_field :logo_out %>
  </div>
  <div class="field">
    <%= f.label :vittoria %><br>
    <%= f.text_field :vittoria %>
  </div>
  <div class="field">
    <%= f.label :pareggio %><br>
    <%= f.text_field :pareggio %>
  </div>
  <div class="field">
    <%= f.label :sconfitta %><br>
    <%= f.text_field :sconfitta %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing Bet</h1>
      <%= form_for @bet do |f| %>

        <div class="field">
          <%= f.label :id %><br>
          <%= f.number_field :id %>
        </div>

        <div class="field">
          <%= f.label :n_giornata %><br>
          <%= f.number_field :n_giornata %>
        </div>
         <div class="field">
          <%= f.label :chiudi_concorso %><br>
          <%= f.text_field :chiudi_concorso %>
        </div>

         <div class="field">
          <%= @bet.evento %><br>
          <%= f.label :risultato %><br>
          <%= f.text_field :risultato %>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>	
      <% end %>

app/views/bets/index.html.erb
<!-- <h1>Listing Bets</h1> -->
  <div class="center"> 
    <%  if !@bets[0].nil? %>
      <h3><%= "Giornata " + @bets[0].n_giornata.to_s %></h3>
    <% end %>
  </div>
  <div class="row">
    <% @bets.each do |bet| %>
      <div class="col s12 m6 l4">
        <div class="card  blue-grey darken-1 altezza-bet">
          <div class="center waves-effect waves-block waves-light">
            <%= image_tag bet.logo_in, class:"tiny material-icons class-logo" %>
            <%= image_tag bet.logo_out, class:"material-icons class-logo" %>     
          </div>
          <div class="card-content">
            <span class="card-title activator white-text"><%= bet.evento %><i class="material-icons right">more_vert</i></span>
            
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= bet.evento %><i class="material-icons right">close</i></span>
            <p>
              <table>
                <thead>
                  <tr>
                    <th>1</th>
                    <th>x</th>
                    <th>2</th>     
                    <th colspan="3"></th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                      <td><%= link_to bet.vittoria, bet_puntates_path(c_u: current_user, :bet => bet.id, :evento_scommesso => "v"), :method => :post %></td>
                      <td><%= link_to  bet.pareggio, bet_puntates_path(c_u: current_user, :bet => bet.id, :evento_scommesso => "p"), :method => :post %></td>
                      <td><%= link_to  bet.sconfitta, bet_puntates_path(c_u: current_user, :bet => bet.id, :evento_scommesso => "s"), :method => :post %></td>
      
                      <% if user_signed_in? %>
                        <% if current_user.email == "vinimp@libero.it" then %>
                          <td><%= link_to 'Show', bet %></td>
                          <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
                          <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
                        <% end %>
                      <% end %>
                    </tr>

                </tbody>
              </table>

            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<br>


<% if user_signed_in? %>
  <% if current_user.email == "vinimp@libero.it" then %>
    
    <td><%= link_to 'Nuovo Concorso', new_bet_path %></td>
    
  <% end %>
<% end %>

<div class="pagination center">
    <%= will_paginate @bets  %>
</div>

app/views/bets/new.html.erb
<h1>New Bet</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p>
  <strong>Evento:</strong>
  <%= @bet.evento %>
</p>

<p>
  <strong>Vittoria:</strong>
  <%= @bet.vittoria %>
</p>

<p>
  <strong>Pareggio:</strong>
  <%= @bet.pareggio %>
</p>

<p>
  <strong>Sconfitta:</strong>
  <%= @bet.sconfitta %>
</p>

<p>
  <strong>Data:</strong>
  <%= @bet.data %>
</p>

<% if current_user == "vinimp@libero.it" %>
  <%= link_to 'Edit', edit_bet_path(@bet) %> |
<% end %>
<%= link_to 'Back', bets_path %>