config/routes.rb
Rails.application.routes.draw do

    Rails.application.routes.draw do
      devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
    end

  resources :eurekas
  resources :classificas
  resources :bet_puntates
  resources :bets
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'schedine' => 'bet_puntates#schedine'

  get 'bilancio' => 'eurekas#bilancio'

  get 'bilancio_edit' => 'eurekas#bilancio_edit'

end

app/models/eureka.rb
class Eureka < ActiveRecord::Base
end

app/controllers/eurekas_controller.rb
class EurekasController < ApplicationController
  before_action :set_eureka, only: [:show, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :bilancio_edit, :show]

  def bilancio_edit
    #@bilancio = Eureka.first
    @bilancio = Eureka.find_by(id: params[:format])
  end

  def bilancio
    @bilancio = Eureka.all.order('id DESC') #.limit(10)   
    @vincita_spesa = 0
    @bilancio.each do |bil|
      if !bil.vincita.nil?
        @vincita_spesa = @vincita_spesa + bil.vincita - bil.puntata11 - bil.puntata1x - bil.puntatax - bil.puntata2
      else
        @vincita_spesa = @vincita_spesa - bil.puntata11 - bil.puntata1x - bil.puntatax - bil.puntata2
      end
    end   
    if !current_user.nil?
      if current_user.admin?
        @bilancio = Eureka.all.order('id DESC').paginate(:page => params[:page], :per_page => 10)
      else
         @bilancio = Eureka.all.order('id DESC').limit(1).paginate(:page => params[:page], :per_page => 10)
      end
    else
       @bilancio = Eureka.limit(1).order('id DESC').paginate(:page => params[:page], :per_page => 10)
    end
  end

  def index
    #@eurekas = Eureka.all

    if !current_user.nil?
      if current_user.admin?
        @eurekas = Eureka.all.order('id DESC').paginate(:page => params[:page], :per_page => 1)
      else
        @eurekas = Eureka.all.order('id DESC').limit(2).paginate(:page => params[:page], :per_page => 1)
      end
    else
      @eurekas = Eureka.all.order('id DESC').limit(2).paginate(:page => params[:page], :per_page => 1)
    end

    if !@eurekas[0].nil?
      @spesa_corrente = (@eurekas[0].puntata11).to_f + (@eurekas[0].puntata1x).to_f + (@eurekas[0].puntatax).to_f + (@eurekas[0].puntata2).to_f
    end
  end

  def show
  end

  def new
    @eureka = Eureka.new
  end

  def edit
    @eureka = Eureka.find_by(id: params[:id])
  end

  def create
    @eureka = Eureka.new(eureka_params)
    respond_to do |format|
      if @eureka.save        
        format.html { redirect_to @eureka, notice: 'Eureka was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @eureka.update(eureka_params)
        format.html { redirect_to @eureka, notice: 'Eureka was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @eureka.destroy
    respond_to do |format|
      format.html { redirect_to eurekas_url, notice: 'Eureka was successfully destroyed.' }
    end
  end

  private
    def set_eureka
      @eureka = Eureka.find(params[:id])
    end

    def eureka_params
      params.require(:eureka).permit(:evento1, :evento2, :unouno, :unox, :x, :due, :puntata11, :puntata1x, :puntatax, :puntata2,
        :data, :spesa, :vincita, :spesa_totale, :vincita_totale)
    end
end

app/helpers/eurekas_helper.rb
module EurekasHelper
end

app/views/eurekas/_form.html.erb
<%= form_for(@eureka) do |f| %>
  <% if @eureka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eureka.errors.count, "error") %> prohibited this eureka from being saved:</h2>

      <ul>
      <% @eureka.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'data evento' %><br>
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :evento1 %><br>
    <%= f.text_field :evento1 %>
  </div>
  <div class="field">
    <%= f.label :evento2 %><br>
    <%= f.text_field :evento2 %>
  </div>
  <div class="field">
    <%= f.label :unouno %><br>
    <%= f.text_field :unouno %>
  </div>
  <div class="field">
    <%= f.label :unox %><br>
    <%= f.text_field :unox %>
  </div>
  <div class="field">
    <%= f.label :x %><br>
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.text_field :due %>
  </div>


  <div class="field">
    <%= f.label :puntata11 %><br>
    <%= f.text_field :puntata11 %>
  </div>
  <div class="field">
    <%= f.label :puntata1x %><br>
    <%= f.text_field :puntata1x %>
  </div>
  <div class="field">
    <%= f.label :puntatax %><br>
    <%= f.text_field :puntatax %>
  </div>
  <div class="field">
    <%= f.label :puntata2 %><br>
    <%= f.text_field :puntata2 %>
  </div>




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eurekas/bilancio.html.erb
<h4 class="center">Bilancio</h4>

      <div class="row">
        <div class="col s3 m3 l2 offset-l2 center">
          <b>Evento</b>
        </div>
        <div class="col s3 m3 l2 center">
          <b>Spesa</b>
        </div>
        <div class="col s3 m3 l2 center">
          <b>Vincita</b>
        </div>  
        <div class="col s3 m3 l2 center">
          <b>Data</b>
        </div>
      </div>

      <div class="row">
        <div class="col s12 m12 l12">
          <div class="card blue-grey darken-1">
            <div class="card-content">
              <% @contatore = 0 %>
              <% @bilancio.each do |bilancio| %>



                <% @contatore = @contatore +1 %>
                <% if @contatore % 2 == 0 %>
                  <% @colore = "testo-verde" %>
                <% else %>
                  <% @colore = "testo-rosso" %>
                <% end %>
                <div class="row">               
                        <div class="col s3 m3 l2 offset-l2 <%= @colore %>">
                          <%= link_to "Incontri", eureka_path(bilancio.id) %> 
                        </div>
                        <div class="col s3 m3 l2 bilancio <%= @colore %>">
                          <%= number_to_currency(bilancio.puntata11 + bilancio.puntata1x + bilancio.puntatax + bilancio.puntata2) %>
                        </div>
                        <div class="col s3 m3 l2 bilancio <%= @colore %>">
                          <%= number_to_currency(bilancio.vincita) %>
                        </div>  


                        <div class="col s3 m3 l2 bilancio <%= @colore %>">
                          <%= bilancio.data.strftime("%d/%m/%Y") %>
                        </div>  
                        <div class="col s1 m1 l2 bilancio">
                          <% if user_signed_in? %>
                            <% if current_user.email == "vinimp@libero.it" then %>
                                  <%= link_to 'Edit', bilancio_edit_path(bilancio)  %>
                            <% end %>
                          <% end %>    
                        </div>  
                </div>                                  
              <% end %>
            </div>
          </div>
        </div>
      </div>

<div class="row">
  <div class="col s6 m3 l2 offset-l5">
    <b>Netto</b>
    <h5 class="chip red accent-1"><b><%= number_to_currency(@vincita_spesa) %></b></h5>
  </div>
</div>

<div class="pagination center">
    <%= will_paginate @bilancio  %>
</div>

app/views/eurekas/bilancio_edit.html.erb
<%= form_for(@bilancio) do |f| %>
  <div class="field">
    <%= f.label :'evento1' %><br>
    <%= f.text_field :evento1 %>
  </div>
  <div class="field">
    <%= f.label :'evento2' %><br>
    <%= f.text_field :evento2 %>
  </div>
  <div class="field">
    <%= f.label :'vincita' %><br>
    <%= f.text_field :vincita %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eurekas/edit.html.erb
<h1>Editing Eureka</h1>

<%= render 'form' %>

<%= link_to 'Show', @eureka %> |
<%= link_to 'Back', eurekas_path %>

app/views/eurekas/index.html.erb
<p id="notice"><%= notice %></p>

<% if @eurekas != nil %>

<div class="row">
  <div class="col s12 m12 l12">
    <h4 class="header center">Scommessa proposta per oggi</h4>
    <div class="card horizontal">
      <div class="card-image blue-grey darken-1">
        <%= image_tag "logo.gif", class: "logo-v-center" %>
      </div>
      <div class="card-stacked">
        <div class="card-content blue-grey darken-1 card-content white-text">



            <% if !@eurekas[0].nil? %>
              <div>
                <b><%= @eurekas[0].evento1 %><br>
                <%= @eurekas[0].evento2 %></b>
              </div>
                <p class="cyan-text lighten-5-text">Data evento: <%= @eurekas[0].data.strftime("%d/%m/%Y") %></p>
                <% end %>
<% end %>


          <div class="row">
            <div class="col s3 col-offset-s3 m3 l3">
              
            </div>  
            <div class="col s2 m2 l2">
              <b>1-1</b><br>
            </div>
            <div class="col s2 m2 l2">
              <b>1-x</b><br>    
            </div>
            <div class="col s2 m2 l2">
              <b>x</b><br>    
            </div>
            <div class="col s2 m2 l2">
              <b>2</b><br>    
            </div>
          </div>

<hr color="red darken-4">
 <% if !@eurekas[0].nil? %>
          <div class="row">
            <div class="col s3 col-offset-s3 m3 l3 testo-quote"> 
              <b>Quote</b> 
            </div>  
            <div class="col s2 m2 l2 testo-quote">
              <%= @eurekas[0].unouno %>
            </div>
            <div class="col s2 m2 l2 testo-quote">   
              <%= @eurekas[0].unox %>
            </div>
            <div class="col s2 m2 l2 testo-quote">  
              <%= @eurekas[0].x %>
            </div>
            <div class="col s2 m2 l2 testo-quote"> 
              <%= @eurekas[0].due %>
            </div>
          </div>

<hr color="red darken-4">          

          <div class="row">
            <div class="col s3 col-offset-s3 m3 l3 testo-verde"> 
              <b>Puntate</b> 
            </div>  
            <div class="col s2 m2 l2 testo-verde">
              <%= number_to_currency(@eurekas[0].puntata11) %>
            </div>
            <div class="col s2 m2 l2 testo-verde">   
              <%= number_to_currency(@eurekas[0].puntata1x) %>
            </div>
            <div class="col s2 m2 l2 testo-verde">  
              <%= number_to_currency(@eurekas[0].puntatax) %>
            </div>
            <div class="col s2 m2 l2 testo-verde"> 
              <%= number_to_currency(@eurekas[0].puntata2) %>
            </div>
          </div>

<hr color="red darken-4">          

          <div class="row">
            <div class="col s3 col-offset-s3 m3 l3 testo-rosso"> 
              <b>Potenziali Vincite</b> 
            </div>  
            <div class="col s2 m2 l2 testo-rosso">
              <b><%= number_to_currency(@eurekas[0].puntata11 * @eurekas[0].unouno) %></b>
            </div>
            <div class="col s2 m2 l2 testo-rosso">   
              <b><%= number_to_currency(@eurekas[0].puntata1x * @eurekas[0].unox) %></b>
            </div>
            <div class="col s2 m2 l2 testo-rosso">  
              <b><%= number_to_currency(@eurekas[0].puntatax * @eurekas[0].x) %></b>
            </div>
            <div class="col s2 m2 l2 testo-rosso"> 
              <b><%= number_to_currency(@eurekas[0].puntata2 * @eurekas[0].due) %></b>
            </div>
          </div>

        </div>   
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col s6 m3 l2 offset-l5">
    <b>Spesa corrente</b>
    <h5 class="chip red accent-1"><b><%= number_to_currency(@spesa_corrente) %></b></h5>
  </div>


<% end %>


<div class="row">
  <div class="col s12 m12 l12" style='text-align:justify'>
    <hr>
    <h4 class="header center">Ratio della scommessa</h4>
    <p><b>Con la scommessa proposta si punta a vincere 10 euri nel caso della sortita degli eventi 1-1 e 1-x, a recuperare l'intera spesa nel caso della sortita del pareggio del primo evento, e di attutire la perdita nel caso della sortita della vittoria della squadra ospite del primo evento</b></p>
  </div>
</div>


<% if user_signed_in? %>
  <% if current_user.email == "vinimp@libero.it" then %>
    <% @eurekas.each do |eureka| %>
        <%= link_to 'Show', eureka %>
        <%= link_to 'Edit', edit_eureka_path(eureka) %>
        <%= link_to 'Destroy', eureka, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>
<% end %>    
<br>

<%= link_to "Bilancio", bilancio_path, class: "btn btn-large" %>
<% if user_signed_in? %>
  <% if current_user.email == "vinimp@libero.it" then %>
    <%= link_to 'New Eureka', new_eureka_path %>
  <% end %>
<% end %>

<% if current_user.admin? %>
  <div class="pagination center">
      <%= will_paginate @bets  %>
  </div>
<% end %>

app/views/eurekas/new.html.erb
<h1>New Eureka</h1>

<%= render 'form' %>

<%= link_to 'Back', eurekas_path %>

app/views/eurekas/show.html.erb
<p id="notice"><%= notice %></p>




<div class="row">
  <div class="col s12 m12 l12">
    <h4 class="header center">Scommessa proposta <br><%= @eureka.evento1 %> - <%= @eureka.evento2 %></h4>
    <div class="card horizontal">
      <div class="card-image blue-grey darken-1">
        <%= image_tag "logo.gif", class: "logo-v-center" %>
      </div>
      <div class="card-stacked">
        <div class="card-content blue-grey darken-1 card-content white-text">

                <p class="cyan-text lighten-5-text">Data evento: <%= @eureka.data.strftime("%d/%m/%Y") %></p>


          <div class="row">
            <div class="col s3 col-offset-s3 m3 l3">
              
            </div>  
            <div class="col s2 m2 l2">
              <b>1-1</b><br>
            </div>
            <div class="col s2 m2 l2">
              <b>1-x</b><br>    
            </div>
            <div class="col s2 m2 l2">
              <b>x</b><br>    
            </div>
            <div class="col s2 m2 l2">
              <b>2</b><br>    
            </div>
          </div>

<hr color="red darken-4">
          <div class="row">
            <div class="col s3 col-offset-s3 m3 l3 testo-quote"> 
              <b>Quote</b> 
            </div>  
            <div class="col s2 m2 l2 testo-quote">
              <%= @eureka.unouno %>
            </div>
            <div class="col s2 m2 l2 testo-quote">   
              <%= @eureka.unox %>
            </div>
            <div class="col s2 m2 l2 testo-quote">  
              <%= @eureka.x %>
            </div>
            <div class="col s2 m2 l2 testo-quote"> 
              <%= @eureka.due %>
            </div>
          </div>

<hr color="red darken-4">          

          <div class="row">
            <div class="col s3 col-offset-s3 m3 l3 testo-verde"> 
              <b>Puntate</b> 
            </div>  
            <div class="col s2 m2 l2 testo-verde">
              <%= number_to_currency(@eureka.puntata11) %>
            </div>
            <div class="col s2 m2 l2 testo-verde">   
              <%= number_to_currency(@eureka.puntata1x) %>
            </div>
            <div class="col s2 m2 l2 testo-verde">  
              <%= number_to_currency(@eureka.puntatax) %>
            </div>
            <div class="col s2 m2 l2 testo-verde"> 
              <%= number_to_currency(@eureka.puntata2) %>
            </div>
          </div>







<% if user_signed_in? %>
  <% if current_user.email == "vinimp@libero.it" then %>
    <%= link_to 'Edit', edit_eureka_path(@eureka) %> |
    <%= link_to 'Back', eurekas_path %>
  <% end %>
<% end %>