config/routes.rb
Rails.application.routes.draw do

    Rails.application.routes.draw do
      devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
    end

  resources :eurekas
  resources :classificas
  resources :bet_puntates
  resources :bets
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'schedine' => 'bet_puntates#schedine'

  get 'bilancio' => 'eurekas#bilancio'

  get 'bilancio_edit' => 'eurekas#bilancio_edit'

end

app/models/bet_puntate.rb
class BetPuntate < ActiveRecord::Base
	belongs_to :user	
	belongs_to :bet
	belongs_to :classifica

	attr_accessible :user, :bet, :evento_scommesso, :user_id, :chiusura, :id, :n_giornata
end

app/controllers/bet_puntates_controller.rb
class BetPuntatesController < ApplicationController
  before_action :set_bet_puntate, only: [:index, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:schedine]

  def schedine
    @classifica = Classifica.order('punteggio DESC')
    @settimana = BetPuntate.order('n_giornata DESC', 'user_id ASC')
    @utente = User.all
    if !@settimana[0].nil?
      @schedine = BetPuntate.where(n_giornata: @settimana[0].n_giornata, user_id: User.distinct).order('user_id ASC')
    else
      @schedine = BetPuntate.where(user_id: User.distinct).order('user_id ASC')
    end
    #@schedine = User.where(id: BetPuntate.where(n_giornata: @settimana[0].n_giornata))
  end

  def index
    $schedina = nil
    @chiusura = false
    @quota_totale = 1
    @controlla_chiusura = BetPuntate.where(:user_id => current_user.id, n_giornata: @ngiornata[0].n_giornata)
    if @controlla_chiusura.count > 0 
      @controlla_chiusura.each do |controlla|
          @chiusura = controlla.chiusura
          if controlla.evento_scommesso == "s"
            @quota_totale = (@quota_totale * controlla.bet(controlla.bet_id)[:sconfitta]) 
          end
          if controlla.evento_scommesso == "v"
            @quota_totale = (@quota_totale * controlla.bet(controlla.bet_id)[:vittoria]) 
          end
          if controlla.evento_scommesso == "p"
            @quota_totale = (@quota_totale * controlla.bet(controlla.bet_id)[:pareggio]) 
          end
      end
    end
  end



  def show
  end

  def new
  end

  def edit
  end


  def create
    @evento_scelto = Bet.find(params[:bet])
    @controllo = BetPuntate.where(bet_id: params[:bet], user_id: params[:c_u])
    if (@controllo.count == 0) && (!@evento_scelto.chiudi_concorso)
      @controllo_scommessa_piazzata = BetPuntate.where(user_id: params[:c_u]).order('n_giornata DESC')
      @bet_puntate = BetPuntate.new
      @bet_puntate.user_id = params[:c_u]
      @bet_puntate.bet_id = params[:bet]
      @bet_puntate.evento_scommesso = params[:evento_scommesso]
      @ngiornata = Bet.order('n_giornata DESC') 

      if (@ngiornata[0].n_giornata == @controllo_scommessa_piazzata[0].n_giornata)
        if (!@controllo_scommessa_piazzata[0].chiusura?)
          @csp = true
        else
          @csp = false
        end
      else
        @csp = true
      end

      if @csp ####################################(!@controllo_scommessa_piazzata[0].chiusura?)
        if @ngiornata[0].n_giornata == @controllo_scommessa_piazzata[0].n_giornata
          if (!@ngiornata[0].chiudi_concorso) && (!@controllo_scommessa_piazzata[0].nil?)
            @bet_puntate.n_giornata = @ngiornata[0].n_giornata
            respond_to do |format|
              if @bet_puntate.save
                $bet_puntate = BetPuntate.find_by bet_id: @bet_puntate.bet_id
                format.html { redirect_to bets_path, notice: 'L ''evento è stato aggiunto alla tua schedina.' }
              else
                format.html { render :new }
              end
            end

          else
            respond_to do |format|
              format.html { redirect_to bets_path, notice: 'Già hai piazzato la tua scommessa' }
            end
          end
        else

          if (!@evento_scelto.chiudi_concorso) && (!@controllo_scommessa_piazzata[0].nil?)
            @bet_puntate.n_giornata = @ngiornata[0].n_giornata
            respond_to do |format|
              if @bet_puntate.save
                $bet_puntate = BetPuntate.find_by bet_id: @bet_puntate.bet_id
                format.html { redirect_to bets_path, notice: 'L ''evento è stato aggiunto alla tua schedina.' }
              else
                format.html { render :new }
              end 
            end 
          else
            respond_to do |format|
              format.html { redirect_to bets_path, notice: 'Evento non più disponibile!!' }
            end
          end
        end 
      else
        @bet_puntate.n_giornata = @ngiornata[0].n_giornata
        if (!@evento_scelto.chiudi_concorso) && (@controllo_scommessa_piazzata[0].nil?)
          respond_to do |format|
            if @bet_puntate.save
              $bet_puntate = BetPuntate.find_by bet_id: @bet_puntate.bet_id
              format.html { redirect_to bets_path, notice: 'L ''evento è stato aggiunto alla tua schedina.' }
            else
              format.html { render :new }
            end
          end
        else
          respond_to do |format|
            format.html { redirect_to bets_path, notice: 'Evento non più disponibile!' }
            #format.html { redirect_to bets_path, notice: @controllo_scommessa_piazzata[0] }
          end
        end  
      end
    

    else
       redirect_to bets_path, notice: 'L ''evento non è disponibile.' 
    end
  end


  def update
    respond_to do |format|
          if BetPuntate.where(:user_id => bet_puntate_params[:user_id]).update_all(chiusura: 'true')
            format.html { redirect_to bet_puntates_path, notice: 'La tua scommessa è stata aggiornata.' }
          else
            format.html { render :edit }
          end
    end
  end


  def destroy
    @bet_puntate.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to bet_puntates_url, notice: 'La tua scommessa è stata eliminata.' }
    end
  end


  private
    def set_bet_puntate
      #@bet_puntates = BetPuntate.where("created_at", params[:bet_data])
      if action_name != 'destroy'
        @bet_puntates = BetPuntate.where("user_id = #{current_user.id}") 
      else
        @bet_puntates = BetPuntate.where("id= #{params[:id]}")
        @bet_puntate = BetPuntate.where("id= #{params[:id]}")   
      end
      @ngiornata = Bet.order('n_giornata DESC')   
    end

    def bet_puntate_params
      params.require(:bet_puntate).permit(:user, :bet, :evento_scommesso, :user_id, :chiusura, :id, :n_gionata)
    end
end

app/helpers/bet_puntates_helper.rb
module BetPuntatesHelper
end

app/views/bet_puntates/_form.html.erb
<%= form_for(@bet_puntate) do |f| %>
  <% if @bet_puntate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet_puntate.errors.count, "error") %> prohibited this bet_puntate from being saved:</h2>

      <ul>
      <% @bet_puntate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :bet_id %><br>
    <%= f.number_field :bet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bet_puntates/edit.html.erb
<h1>Editing Bet Puntate</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet_puntate %> |
<%= link_to 'Back', bet_puntates_path %>

app/views/bet_puntates/index.html.erb
<table class="container">
  <thead>
    <tr>
      <th><h2 class="center">La mia scommessa</h2></th>
      <th><h5 class="chip red accent-1"><b><%= number_to_percentage(@quota_totale, precision: 2) %></b></h5></th>
    </tr>
  </thead>
</table>

<table class="container">
  <thead>
    <tr>
      <th>Incontro</th>
      <th class="center">Evento scommesso</th>
      <th class="center">Quota</th>      
    </tr>
  </thead>


  <tbody>
    <% if @bet_puntates != nil %>
      <% @controlla_chiusura.each do |bet| %>
      <tr>
        <td><%= bet.bet.evento %></td>
        <% if bet.evento_scommesso == "v"%>
          <td class="center">1</td>
          <td class="center"><%= bet.bet.vittoria %></td>          
        <% end %>
        <% if bet.evento_scommesso == "p"%>
          <td class="center">x</td>
          <td class="center"><%= bet.bet.pareggio %></td>           
        <% end %>      
        <% if bet.evento_scommesso == "s"%>
          <td class="center">2</td>
          <td class="center"><%= bet.bet.sconfitta %></td>           
        <% end %>
        <% if !@chiusura %>
          <td class="center"><%= link_to "Elimina", bet, method: :delete, data: { confirm: 'Sei sicuro?' }  %></td> 
        <% end %>
      </tr>
      <% end %>
    <% end %>
      <tr>
        <td colspan="3" class="center">  
          <% if !@chiusura %>
            <% if !@bet_puntate.nil? %>
              <%= form_for @bet_puntate, html: { multipart: true } do |f| %>
                <%= f.hidden_field :user_id %>
                <div class="actions">
                  <%= f.submit "Piazza la scommessa", class: "waves-effect waves-light btn btn-custom" %>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
  </tbody>
</table>

<br>

app/views/bet_puntates/new.html.erb
<h1>New Bet Puntate</h1>

<%= render 'form' %>

<%= link_to 'Back', bet_puntates_path %>

app/views/bet_puntates/schedine.html.erb
<div class="row">
  <div class="col s11 m11">


      <div class="row">
        <div class="col s12 m12">
          <h4 class="center">Le giocate dei partecipanti alla gara</h4>
        </div>
        <% if !@settimana[0].nil? %>
          <div class="col s12 m6"><h5 class="colore"><u>Settimana <%= @settimana[0].n_giornata %></u></h5>
        <% end %>
        </div>
      </div>  

      <div class="row">
        <% @controllo = -1 %>
        <% @metti_div = true %>
        <% @contatore = 0 %>  
        <% @contatore_colore = 0 %>
        <% @schedine.each do |schedina| %>
            <% @utente = User.find_by(id:schedina.user_id) %> 
            <% if schedina.chiusura %>
              <% if @controllo != schedina.user_id %> 
                </div>
                <div class="row">
                <br><% @controllo = schedina.user_id %>
                <h5 class="colore center"><%= @utente.name %></h5>
                <% @contatore_colore = @contatore_colore +1 %> 

                <% if @contatore_colore % 2 == 0 %>
                  <% @colore = "green darken-1" %>         
                <% else %>
                  <% @colore = "blue-grey darken-1" %>
                <% end %>
              <% end %>
            <div class="col s12 m6 l6">
              <div class="card horizontal ">
                <div class="card-image <%= @colore %>">
                  <%= image_tag "logo.gif", class: "logo-v-center" %>
                </div>
                <div class="schedina card-stacked <%= @colore %>">
                  <div class="card-content white-text">

                    <% @evento = Bet.find_by(id: schedina.bet_id) %>
                    <div class="col s10 m10 l10"><b><%= @evento.evento %></div>
                    <% if schedina.evento_scommesso =="v" %>
                      <div class="col s2 m2 l2 colore_pronostico"><b><%= "1" %></b></div>
                    <% end %>            
                    <% if schedina.evento_scommesso =="p" %>
                      <div class="col s2 m2 l2 colore_pronostico"><b><%= "x" %></b></div>  
                    <% end %>
                    <% if schedina.evento_scommesso =="s" %>
                      <div class="col s2 m2 l2 colore_pronostico"><b><%= "2" %></b></div> 
                    <% end %>
                  </div>
                </div>

                <% end %>

              </div>
            </div>
          <% @contatore = @contatore + 1 %>
        <% end %>
    </div>
  </div>
</div>

app/views/bet_puntates/show.html.erb
<p>
  <strong>User:</strong>
  <%= @bet_puntate.user_id %>
</p>

<p>
  <strong>Bet:</strong>
  <%= @bet_puntate.bet_id %>
</p>

<%= link_to 'Edit', edit_bet_puntate_path(@bet_puntate) %> |
<%= link_to 'Back', bet_puntates_path %>