config/routes.rb
Rails.application.routes.draw do

    Rails.application.routes.draw do
      devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
    end

  resources :eurekas
  resources :classificas
  resources :bet_puntates
  resources :bets
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'schedine' => 'bet_puntates#schedine'

  get 'bilancio' => 'eurekas#bilancio'

  get 'bilancio_edit' => 'eurekas#bilancio_edit'

end

app/views/layouts/_footer.html.erb
<footer class="page-footer teal lighten-3 center">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s4">
          © 2017 Vinimp.top
        </div>
        <div class="col s4">
          <a href="" target="_blank"><i class="fa-social fa fa-facebook-official fa-2x white-text"></i></a>
          <a href="" target="_blank"><i class="fa-social fa fa-twitter fa-2x white-text"></i></a>
        </div>
        <div class="col s4">
          <%= link_to "About", about_path, class:"grey-text text-lighten-4 right" %>
<script type="text/javascript" src="https://counter10.fcs.ovh/private/counter.js?c=b91246229dea61cad9dd2e7fe746084a"></script>
<noscript><a href="https://www.contatoreaccessi.com" title="contatori visite"><img src="https://counter10.fcs.ovh/private/contatoreaccessi.php?c=b91246229dea61cad9dd2e7fe746084a" border="0" title="contatori visite" alt="contatori visite"></a></noscript>


        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb

	<nav class="teal lighten-3">
		<div class="container nav-wrapper">
			<%= image_tag "logo.ico", class: "tiny material-icons class-logo" %>
		  <%= link_to "Vinimp-Bet", root_path, class: "brand-logo testo-logo" %>
		  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>


		  
		  <ul class="right hide-on-med-and-down">		
			<% if user_signed_in? %>
				<% if @bet_puntate != nil %>	  
					<% if controller.controller_name != "bet_puntates" %>
			      <li><%= link_to "Schedina", bet_puntates_path(:user_id => @bet_puntate.user_id), class:"waves-effect waves-light btn" %></li>
			  	<% end %>
				<% end %>	
					
			  <li><%= image_tag current_user.avatar.url(:thumb), class: "tiny material-icons class-logo" %></li>
		  	<li class="colore"><b><%= current_user.name %></b></li>
				<li><a class="dropdown-button teal lighten-3" href="#!" data-activates="dropdown1">Menù<i class="material-icons right">arrow_drop_down</i></a></li>		 
				<ul id="dropdown1" class="dropdown-content">
					<li><%= link_to "Home", root_path %></li>
				  <li><%= link_to "Quote", bets_path %></li>
				  <li><%= link_to "Classifica", classificas_path %></li>
				  <li><%= link_to "Pronostici", schedine_path %></li>	
				  <li class="divider"></li>			
				  <li><%= link_to "Eureka", eurekas_path %></li>		
				  <li><%= link_to "Bilancio", bilancio_path %></li>				  
				  <li class="divider"></li>
				  <li><%= link_to "Account", edit_user_registration_path %></li>
				  <li class="divider"></li>
				  <li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>
				</ul>					  		
			<% else %>
				<li><a class="dropdown-button teal lighten-3" href="#!" data-activates="dropdown1">Menù<i class="material-icons right">arrow_drop_down</i></a></li>		  		
				<ul id="dropdown1" class="dropdown-content">
					<li><%= link_to "Home", root_path %></li>
				  <li><%= link_to "Quote", bets_path %></li>
				  <li><%= link_to "Classifica", classificas_path %></li>
				  <li><%= link_to "Pronostici", schedine_path %></li>	
				  <li class="divider"></li>			
				  <li><%= link_to "Eureka", eurekas_path %></li>		
				  <li><%= link_to "Bilancio", bilancio_path %></li>				  
				</ul>					  		
				<li><%= link_to "Log in", new_user_session_path %></li>
				<li><%= link_to "Registrazione", new_user_registration_path %></li>
			<% end %>		
			</ul>
		  <ul class="side-nav" id="mobile-demo">
		  	<% if user_signed_in? %>
			    <% if $bet_puntate %>
			      <li><%= link_to "Schedina", bet_puntates_path(:bet_data => $bet_puntate.created_at), class:"waves-effect waves-light btn", :target => "_blank" %></li>
			    <% end %>		 
					<li><%= link_to "Home", root_path %></li>
				  <li><%= link_to "Quote", bets_path %></li>
				  <li><%= link_to "Classifica", classificas_path %></li>
				  <li><%= link_to "Pronostici", schedine_path %></li>		
				  <li class="divider"></li>			
				  <li><%= link_to "Eureka", eurekas_path %></li>		
				  <li><%= link_to "Bilancio", bilancio_path %></li>				  		  
				  <li class="divider"></li>
				  <li><%= link_to "Account", edit_user_registration_path %></li>
				  <li class="divider"></li>
		  		<li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>
		  	<% else %>
					<li><%= link_to "Home", root_path %></li>
				  <li><%= link_to "Quote", bets_path %></li>
				  <li><%= link_to "Classifica", classificas_path %></li>
				  <li><%= link_to "Pronostici", schedine_path %></li>	
				  <li class="divider"></li>			
				  <li><%= link_to "Eureka", eurekas_path %></li>		
				  <li><%= link_to "Bilancio", bilancio_path %></li>				  					  					  
					<li><%= link_to "Registrazione", new_user_registration_path %></li>				  
					<li><%= link_to "Log in", new_user_session_path %></li>
				</ul>						
			<% end %>
			</ul>
		</div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VinimpBet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body class="light-blue-text text-darken-4">

<%= render "layouts/header" %>
  <% flash.each do |type, message| %>
    <script>
      Materialize.toast('<%= message %>', 4000)
    </script>
  <% end %>
<%= render 'pages/slider' if action_name == 'home' %>
<main class="container">
	<%= yield %>
</main>

<%= debug(params) if Rails.env.development? %>    

<%= render "layouts/footer" %>

</body>
<script>
  $(".button-collapse").sideNav();
</script>
<script>
  $(document).ready(function(){
    $('ul.tabs').tabs();
  });
</script>
<script>
  $(document).ready(function(){
    $('.parallax').parallax();
  });
</script>
<script>
  $(document).ready(function(){
      $('.tooltipped').tooltip({delay: 50});
    });
</script>
<script>
  $(document).ready(function(){
    $(".dropdown-button").dropdown();
  });
</script>
</html>